// Generated by CoffeeScript 1.8.0
var castMessageBus, castReceiverManager, namespace;

namespace = 'urn:x-cast:com.renolc.cards';

castReceiverManager = cast.receiver.CastReceiverManager.getInstance();

castMessageBus = castReceiverManager.getCastMessageBus(namespace, cast.receiver.CastMessageBus.MessageType.JSON);

castMessageBus.onMessage = function(event) {
  console.log('--message received--');
  return console.log(event);
};

castReceiverManager.onSenderDisconnected = function(event) {
  return console.log('onSenderDisconnected');
};

castReceiverManager.start();

console.log('receiver started');
