// Generated by CoffeeScript 1.8.0
var castMessageBus, castReceiverManager, namespace;

namespace = 'urn:x-cast:com.renolc.cards';

castReceiverManager = cast.receiver.CastReceiverManager.getInstance();

castMessageBus = castReceiverManager.getCastMessageBus(namespace, cast.receiver.CastMessageBus.MessageType.JSON);

castMessageBus.onMessage = function(event) {
  console.log('--message received--');
  console.log(event);
  return document.body.innerHTML += event.data.bork + '<br>';
};

castReceiverManager.onSenderDisconnected = function(event) {
  console.log('onSenderDisconnected');
  return window.close();
};

castReceiverManager.start();

console.log('receiver started');
