// Generated by CoffeeScript 1.8.0
var appid, init, input, namespace, onError, onInitSuccess, receiverListener, session, sessionListener, submit;

namespace = 'urn:x-cast:com.renolc.cards';

appid = 'E1B87031';

input = document.getElementById("text");

submit = document.getElementById("submit");

session = null;

window['__onGCastApiAvailable'] = function(loaded, errorInfo) {
  if (loaded) {
    return init();
  } else {
    return console.log(errorInfo);
  }
};

init = function() {
  var apiConfig, sessionRequest;
  sessionRequest = new chrome.cast.SessionRequest(appid);
  apiConfig = new chrome.cast.ApiConfig(sessionRequest, sessionListener, receiverListener);
  return chrome.cast.initialize(apiConfig, onInitSuccess, onError);
};

receiverListener = function(e) {
  console.log('receiverListener');
  return console.log(e);
};

sessionListener = function(e) {
  session = e;
  console.log('sessionListener');
  return console.log(e);
};

onInitSuccess = function() {
  return console.log('onInitSuccess');
};

onError = function(e) {
  console.log('onError');
  return console.log(e);
};

submit.onclick = function() {
  return session.sendMessage(namespace, {
    'bork': input.value
  });
};
