// Generated by CoffeeScript 1.8.0
var CastReceiver;

CastReceiver = (function() {
  function CastReceiver(namespace) {
    this.namespace = namespace;
    this.manager = cast.receiver.CastReceiverManager.getInstance();
    this.messageBus = this.manager.getCastMessageBus(this.namespace, cast.receiver.CastMessageBus.MessageType.JSON);
    this.messageBus.onMessage = this.onMessage;
    this.manager.start();
  }

  CastReceiver.prototype.onMessage = function(event) {
    console.log('--message received--');
    return console.log(event);
  };

  return CastReceiver;

})();
