// Generated by CoffeeScript 1.8.0
var PIXIRenderer,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

PIXIRenderer = (function() {
  function PIXIRenderer(bgColor, width, height) {
    this.animate = __bind(this.animate, this);
    this.stage = new PIXI.Stage(bgColor);
    this.renderer = PIXI.autoDetectRenderer(width, height);
    document.body.appendChild(this.renderer.view);
    requestAnimFrame(this.animate);
  }

  PIXIRenderer.prototype.animate = function() {
    requestAnimFrame(this.animate);
    return this.renderer.render(this.stage);
  };

  return PIXIRenderer;

})();
